package dev.biserman.planet.planet.ecology.earthlike_clades

import dev.biserman.planet.planet.ecology.ColorTrait
import dev.biserman.planet.planet.ecology.CommonTrait
import dev.biserman.planet.planet.ecology.EarthSpeciesCatalog
import dev.biserman.planet.planet.ecology.SizeClass

val bird = EarthSpeciesCatalog.animal(
    "bird",
    SizeClass.SMALL,
    CommonTrait.ENDOTHERMY,
    CommonTrait.FEATHERS,
    CommonTrait.WINGS,
    CommonTrait.BEAK,
    CommonTrait.TERRESTRIAL_OVOSPORE,
    CommonTrait.OVOSPORE_NEST,
    CommonTrait.DIURNAL,
    CommonTrait.COLLECTIVE_LIVING,
    ColorTrait.BROWN_CAMOUFLAGE
)

val birdMinorClades = listOf(
    bird.extend(
        "ratite",
        SizeClass.MEDIUM,
        CommonTrait.WALKING_LIMBS,
        CommonTrait.GRAZING_MOUTHPARTS,
        CommonTrait.LONG_NECK,
        CommonTrait.HERDING_BEHAVIOR,
        CommonTrait.COLLECTIVE_LIVING,
        minus = listOf(CommonTrait.WINGS)
    ),
    bird.extend(
        "fowl",
        SizeClass.SMALL,
        CommonTrait.WALKING_LIMBS,
        CommonTrait.GRAZING_MOUTHPARTS,
        CommonTrait.SEED_CRACKING_MOUTHPARTS,
        CommonTrait.FREQUENT_REPRODUCTION,
        CommonTrait.HERDING_BEHAVIOR,
        CommonTrait.COLLECTIVE_LIVING
    ),
    bird.extend(
        "crane",
        SizeClass.MEDIUM,
        CommonTrait.WADING_LIMBS,
        CommonTrait.SEED_CRACKING_MOUTHPARTS,
        CommonTrait.SPEAR_BILL,
        CommonTrait.REGIONAL_MIGRATION,
        CommonTrait.WATERPROOF_PLUMAGE,
        ColorTrait.WHITE_CAMOUFLAGE
    ),
    bird.extend(
        "gull",
        SizeClass.SMALL,
        CommonTrait.WADING_LIMBS,
        CommonTrait.SCAVENGING_SENSES,
        CommonTrait.WATERPROOF_PLUMAGE,
        ColorTrait.PALE_CAMOUFLAGE
    ),
    bird.extend(
        "hummingbird",
        SizeClass.TINY,
        CommonTrait.FAST_METABOLISM,
        CommonTrait.NECTAR_SIPPING_TONGUE,
        CommonTrait.POLLEN_CARRYING_SURFACES,
        CommonTrait.LONG_MIGRATION,
        CommonTrait.CHIRPING_CALL,
        CommonTrait.COMPLEX_VOCALIZATIONS
    ),
    bird.extend(
        "penguin",
        SizeClass.SMALL,
        CommonTrait.AQUATIC_FLIPPERS,
        CommonTrait.PROLONGED_BREATH_HOLDING,
        CommonTrait.SEA_ICE_ROOKERY,
        CommonTrait.MOTION_TRACKING_SENSES,
        CommonTrait.BURROW_BORROWER,
        CommonTrait.WATERPROOF_PLUMAGE,
        CommonTrait.FAT_RESERVES,
        CommonTrait.TRUMPETING_CALL,
        ColorTrait.COUNTERSHADE_CAMOUFLAGE
    ),
    bird.extend(
        "owl",
        SizeClass.SMALL, CommonTrait.HOOKED_TALONS, CommonTrait.MOTION_TRACKING_SENSES, CommonTrait.KEEN_HEARING, CommonTrait.SILENT_MOVEMENT, CommonTrait.INSULATING_PLUMAGE, CommonTrait.HOOTING_CALL, CommonTrait.NOCTURNAL
    ),
    bird.extend(
        "hawk",
        SizeClass.SMALL,
        CommonTrait.AMBUSH_MUSCULATURE,
        CommonTrait.KEEN_EYESIGHT,
        CommonTrait.MOTION_TRACKING_SENSES,
        CommonTrait.HOOKED_TALONS
    ),
    bird.extend(
        "vulture",
        SizeClass.SMALL,
        CommonTrait.SCAVENGING_SENSES,
        CommonTrait.RESILIENT_DIGESTION,
        CommonTrait.LONG_MIGRATION
    ),
    bird.extend(
        "hornbill",
        SizeClass.SMALL,
        CommonTrait.CLIMBING_LIMBS,
        CommonTrait.FRUIT_EATING_MOUTHPARTS,
        CommonTrait.CROAKING_CALL,
        ColorTrait.BLACK_CAMOUFLAGE
    ),
    bird.extend(
        "woodpecker",
        SizeClass.SMALL,
        CommonTrait.CLIMBING_LIMBS,
        CommonTrait.AMBUSH_MUSCULATURE,
        CommonTrait.DIGGING_LIMBS,
        CommonTrait.BURROW_BUILDER,
        CommonTrait.DRUMMING_DISPLAY
    ),
    bird.extend(
        "songbird",
        SizeClass.TINY,
        CommonTrait.SEED_CRACKING_MOUTHPARTS,
        CommonTrait.AMBUSH_MUSCULATURE,
        CommonTrait.CHIRPING_CALL,
        CommonTrait.REGIONAL_MIGRATION
    ),
    bird.extend(
        "parrot",
        SizeClass.SMALL,
        CommonTrait.SEED_CRACKING_MOUTHPARTS,
        CommonTrait.CLIMBING_LIMBS,
        CommonTrait.EXTENDED_PARENTAL_CARE,
        CommonTrait.IMITATIVE_VOCALIZATION,
        CommonTrait.INTELLIGENT
    ),
    bird.extend(
        "corvid",
        SizeClass.SMALL,
        CommonTrait.SEED_CRACKING_MOUTHPARTS,
        CommonTrait.SCAVENGING_SENSES,
        CommonTrait.TOOL_MANIPULATION,
        CommonTrait.INTELLIGENT,
        CommonTrait.CROAKING_CALL,
        ColorTrait.BLACK_CAMOUFLAGE
    ),
)
